### ISSUE TITLE
How to edit theme?

### ISSUE THREAD

**Issue by smac89** [abhibagul/Morpho-Blogger-Template#1]
Hi, I love the theme, and would like to modify it to fit my needs. What editor do you use to change the themes?

I am trying to use webstorm, but it does not understand the xml schema and I'm just getting errors everywhere.

**Comment by abhibagul** [comment]
The themes are coded in notepad.

**Comment by smac89** [comment]
Thanks for the reply. I have my work cut out for me it seems
